### ISSUE TITLE
2 nodes connecting failed when RAY_TLS is enabled.

### ISSUE THREAD

**Issue by xiaoran33** [ray-project/rayfed#52]
Node status is OK once TLS is enabled:
```
======== Autoscaler status: 2023-02-07 10:08:08.216389 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_2a321ba103a914821571f010bd317d56425a7552405a068dc7f245b7
 1 node_06e9368d851e3ba77f7a8a91076ff977fad89b5ba2f37b75588ce718
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/4.0 CPU
 0.00/25.844 GiB memory
 0.00/11.929 GiB object_store_memory
 0.0/8.0 promoter
 0.0/8.0 provider

Demands:
 (no resource demands)
```
The following script failed:

error message is ：

```
2023-02-07 10:09:57.143117: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-07 10:10:04,480 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:10:11,496 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:10:18,512 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:10:25,526 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:10:32,540 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:10:39,558 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:10:46,577 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:10:53,592 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:00,606 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:07,621 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:14,637 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:21,653 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:28,668 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:35,684 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:42,701 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:49,717 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:11:56,734 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:12:03,751 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:12:10,765 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-07 10:12:17,780 WARNING utils.py:1242 -- Unable to connect to GCS at 192.168.227.195:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
Traceback (most recent call last):
  File "test-get-data.py", line 7, in <module>
    sf.init(address='192.168.227.195:6379')
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/secretflow/device/driver.py", line 215, in init
    ray.init(
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/ray/worker.py", line 1101, in init
    _global_node = ray.node.Node(
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/ray/node.py", line 185, in __init__
    session_name = ray._private.utils.internal_kv_get_with_retry(
  File "/root/miniconda3/envs/wefe-python-3.8/lib/python3.8/site-packages/ray/_private/utils.py", line 1258, in internal_kv_get_with_retry
    raise RuntimeError(
RuntimeError: Could not read 'session_name' from GCS. Did GCS start successfully?
```

versions:
secretflow-ray               2.0.0.dev1

**Comment by jovany-wang** [comment]
As Ray is a global community, I updated description to English.

**Comment by zhouaihui** [comment]
This issue seems have nothing to do with RayFed. Should we move it to ant-ray or ray? @jovany-wang

**Comment by jovany-wang** [comment]
> This issue seems have nothing to do with RayFed. Should we move it to ant-ray or ray? @jovany-wang 

Yes. You are right. Let us move it to Ray repo after I do a double check.

**Comment by jovany-wang** [comment]
This is due to the wrong configurations in dockers. So close it.
