### ISSUE TITLE
Failed to execute `pip install -e .`

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/rayfed#94]
The error message of executing `pip install -e . -v`:
```bash
-> % pip install -e . -v
Using pip 22.2.2 from /Users/qingwang/anaconda3/lib/python3.9/site-packages/pip (python 3.9)
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Obtaining file:///Users/qingwang/workspace/opensource/RayFed
  Running command pip subprocess to install build dependencies
  Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
  Collecting flit_core<4,>=3.2
    Downloading https://mirrors.aliyun.com/pypi/packages/04/ac/f91a0219e0d4162762f218e4876bf328f16e4d283e691cd7f42a02b22634/flit_core-3.8.0-py3-none-any.whl (62 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 272.8 kB/s eta 0:00:00
  Installing collected packages: flit_core
  Successfully installed flit_core-3.8.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  Traceback (most recent call last):
    File "/Users/qingwang/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/qingwang/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/qingwang/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
      return hook(config_settings)
    File "/private/var/folders/q4/6c8j2fsx34v45njdq0vdkhlm0000gp/T/pip-build-env-svvukwe7/overlay/lib/python3.9/site-packages/flit_core/buildapi.py", line 31, in get_requires_for_build_wheel
      module = Module(info.module, Path.cwd())
    File "/private/var/folders/q4/6c8j2fsx34v45njdq0vdkhlm0000gp/T/pip-build-env-svvukwe7/overlay/lib/python3.9/site-packages/flit_core/common.py", line 59, in __init__
      raise ValueError("No file/folder found for module {}".format(name))
  ValueError: No file/folder found for module RayFed
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/qingwang/anaconda3/bin/python /Users/qingwang/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_editable /var/folders/q4/6c8j2fsx34v45njdq0vdkhlm0000gp/T/tmp3fvd7gfx
  cwd: /Users/qingwang/workspace/opensource/RayFed
  Getting requirements to build editable ... error
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jovany-wang** [comment]
This is due to we introduced `pyproject.yml`.
